wa:
  config:
    dir: "D://whatsapp4j/data"

server:
  port: 8086

openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com
    key: <OPEN-API-KEY>

logging:
  level:
    root: INFO
  file:
    name: logs/app.log
    path: logs